version: '3.8'

services:
  web:
    #build: ./app
    image: medvm/djando_dc_e4:djando_dc_e4
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    #env_file:
    #  - ./.env.dev
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #env_file:
    #  - .env.pgdb
    environment:
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
  nginx:
    #build: ./nginx
    image: medvm/nginx_dc_e4:nginx_dc_e4
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      #- 8080:80
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
